

// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!



#include <stdbool.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
	// We also try to prevent mixing versions of shared uniffi header structs.
	// If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V6
	#ifndef UNIFFI_SHARED_HEADER_V6
		#error Combining helper code from multiple versions of uniffi is not supported
	#endif // ndef UNIFFI_SHARED_HEADER_V6
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V6
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V6 in this file.           ⚠️

typedef struct RustBuffer {
	uint64_t capacity;
	uint64_t len;
	uint8_t *data;
} RustBuffer;

typedef struct ForeignBytes {
	int32_t len;
	const uint8_t *data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
	int8_t code;
	RustBuffer errorBuf;
} RustCallStatus;

#endif // UNIFFI_SHARED_H


#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t data, int8_t poll_result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiRustFutureContinuationCallback(
				UniffiRustFutureContinuationCallback cb, uint64_t data, int8_t poll_result)
{
	return cb(data, poll_result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
typedef void (*UniffiForeignFutureDroppedCallback)(uint64_t handle);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureDroppedCallback(
				UniffiForeignFutureDroppedCallback cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t handle);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceFree(
				UniffiCallbackInterfaceFree cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
typedef uint64_t (*UniffiCallbackInterfaceClone)(uint64_t handle);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static uint64_t call_UniffiCallbackInterfaceClone(
				UniffiCallbackInterfaceClone cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
typedef struct UniffiForeignFutureDroppedCallbackStruct {
    uint64_t handle;
    UniffiForeignFutureDroppedCallback free;
} UniffiForeignFutureDroppedCallbackStruct;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
typedef struct UniffiForeignFutureResultU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t callback_data, UniffiForeignFutureResultU8 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU8(
				UniffiForeignFutureCompleteU8 cb, uint64_t callback_data, UniffiForeignFutureResultU8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
typedef struct UniffiForeignFutureResultI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t callback_data, UniffiForeignFutureResultI8 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI8(
				UniffiForeignFutureCompleteI8 cb, uint64_t callback_data, UniffiForeignFutureResultI8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
typedef struct UniffiForeignFutureResultU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t callback_data, UniffiForeignFutureResultU16 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU16(
				UniffiForeignFutureCompleteU16 cb, uint64_t callback_data, UniffiForeignFutureResultU16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
typedef struct UniffiForeignFutureResultI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t callback_data, UniffiForeignFutureResultI16 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI16(
				UniffiForeignFutureCompleteI16 cb, uint64_t callback_data, UniffiForeignFutureResultI16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
typedef struct UniffiForeignFutureResultU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t callback_data, UniffiForeignFutureResultU32 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU32(
				UniffiForeignFutureCompleteU32 cb, uint64_t callback_data, UniffiForeignFutureResultU32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
typedef struct UniffiForeignFutureResultI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t callback_data, UniffiForeignFutureResultI32 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI32(
				UniffiForeignFutureCompleteI32 cb, uint64_t callback_data, UniffiForeignFutureResultI32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
typedef struct UniffiForeignFutureResultU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t callback_data, UniffiForeignFutureResultU64 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU64(
				UniffiForeignFutureCompleteU64 cb, uint64_t callback_data, UniffiForeignFutureResultU64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
typedef struct UniffiForeignFutureResultI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t callback_data, UniffiForeignFutureResultI64 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI64(
				UniffiForeignFutureCompleteI64 cb, uint64_t callback_data, UniffiForeignFutureResultI64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
typedef struct UniffiForeignFutureResultF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t callback_data, UniffiForeignFutureResultF32 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF32(
				UniffiForeignFutureCompleteF32 cb, uint64_t callback_data, UniffiForeignFutureResultF32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
typedef struct UniffiForeignFutureResultF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t callback_data, UniffiForeignFutureResultF64 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF64(
				UniffiForeignFutureCompleteF64 cb, uint64_t callback_data, UniffiForeignFutureResultF64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
typedef struct UniffiForeignFutureResultRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t callback_data, UniffiForeignFutureResultRustBuffer result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteRustBuffer(
				UniffiForeignFutureCompleteRustBuffer cb, uint64_t callback_data, UniffiForeignFutureResultRustBuffer result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
typedef struct UniffiForeignFutureResultVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureResultVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t callback_data, UniffiForeignFutureResultVoid result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteVoid(
				UniffiForeignFutureCompleteVoid cb, uint64_t callback_data, UniffiForeignFutureResultVoid result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_ANALYTICS_HOST_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_ANALYTICS_HOST_METHOD0
typedef void (*UniffiCallbackInterfaceBindingAnalyticsHostMethod0)(uint64_t uniffi_handle, RustBuffer event, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceBindingAnalyticsHostMethod0(
				UniffiCallbackInterfaceBindingAnalyticsHostMethod0 cb, uint64_t uniffi_handle, RustBuffer event, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, event, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_ANALYTICS_HOST_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_ANALYTICS_HOST_METHOD1
typedef void (*UniffiCallbackInterfaceBindingAnalyticsHostMethod1)(uint64_t uniffi_handle, RustBuffer payload, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceBindingAnalyticsHostMethod1(
				UniffiCallbackInterfaceBindingAnalyticsHostMethod1 cb, uint64_t uniffi_handle, RustBuffer payload, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, payload, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_ANALYTICS_HOST_METHOD2
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_ANALYTICS_HOST_METHOD2
typedef void (*UniffiCallbackInterfaceBindingAnalyticsHostMethod2)(uint64_t uniffi_handle, RustBuffer payload, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceBindingAnalyticsHostMethod2(
				UniffiCallbackInterfaceBindingAnalyticsHostMethod2 cb, uint64_t uniffi_handle, RustBuffer payload, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, payload, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_ANALYTICS_HOST_METHOD3
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_ANALYTICS_HOST_METHOD3
typedef void (*UniffiCallbackInterfaceBindingAnalyticsHostMethod3)(uint64_t uniffi_handle, RustBuffer space_person_id, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceBindingAnalyticsHostMethod3(
				UniffiCallbackInterfaceBindingAnalyticsHostMethod3 cb, uint64_t uniffi_handle, RustBuffer space_person_id, RustBuffer* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, space_person_id, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_ANALYTICS_HOST_METHOD4
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_ANALYTICS_HOST_METHOD4
typedef void (*UniffiCallbackInterfaceBindingAnalyticsHostMethod4)(uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceBindingAnalyticsHostMethod4(
				UniffiCallbackInterfaceBindingAnalyticsHostMethod4 cb, uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_ANALYTICS_HOST_METHOD5
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_ANALYTICS_HOST_METHOD5
typedef void (*UniffiCallbackInterfaceBindingAnalyticsHostMethod5)(uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceBindingAnalyticsHostMethod5(
				UniffiCallbackInterfaceBindingAnalyticsHostMethod5 cb, uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_ANALYTICS_HOST_METHOD6
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_ANALYTICS_HOST_METHOD6
typedef void (*UniffiCallbackInterfaceBindingAnalyticsHostMethod6)(uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceBindingAnalyticsHostMethod6(
				UniffiCallbackInterfaceBindingAnalyticsHostMethod6 cb, uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_HOST_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_HOST_METHOD0
typedef void (*UniffiCallbackInterfaceBindingHostMethod0)(uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceBindingHostMethod0(
				UniffiCallbackInterfaceBindingHostMethod0 cb, uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_HOST_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_HOST_METHOD1
typedef void (*UniffiCallbackInterfaceBindingHostMethod1)(uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceBindingHostMethod1(
				UniffiCallbackInterfaceBindingHostMethod1 cb, uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_HOST_METHOD2
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_HOST_METHOD2
typedef void (*UniffiCallbackInterfaceBindingHostMethod2)(uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceBindingHostMethod2(
				UniffiCallbackInterfaceBindingHostMethod2 cb, uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_HOST_METHOD3
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_HOST_METHOD3
typedef void (*UniffiCallbackInterfaceBindingHostMethod3)(uint64_t uniffi_handle, RustBuffer key, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceBindingHostMethod3(
				UniffiCallbackInterfaceBindingHostMethod3 cb, uint64_t uniffi_handle, RustBuffer key, RustBuffer* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, key, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_HOST_METHOD4
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_HOST_METHOD4
typedef void (*UniffiCallbackInterfaceBindingHostMethod4)(uint64_t uniffi_handle, RustBuffer key, RustBuffer value, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceBindingHostMethod4(
				UniffiCallbackInterfaceBindingHostMethod4 cb, uint64_t uniffi_handle, RustBuffer key, RustBuffer value, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, key, value, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_HOST_METHOD5
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_HOST_METHOD5
typedef void (*UniffiCallbackInterfaceBindingHostMethod5)(uint64_t uniffi_handle, RustBuffer key, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceBindingHostMethod5(
				UniffiCallbackInterfaceBindingHostMethod5 cb, uint64_t uniffi_handle, RustBuffer key, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, key, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_HOST_METHOD6
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_HOST_METHOD6
typedef void (*UniffiCallbackInterfaceBindingHostMethod6)(uint64_t uniffi_handle, RustBuffer handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceBindingHostMethod6(
				UniffiCallbackInterfaceBindingHostMethod6 cb, uint64_t uniffi_handle, RustBuffer handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, handle, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_HOST_METHOD7
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_HOST_METHOD7
typedef void (*UniffiCallbackInterfaceBindingHostMethod7)(uint64_t uniffi_handle, RustBuffer handle, uint64_t offset, uint32_t max_bytes, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceBindingHostMethod7(
				UniffiCallbackInterfaceBindingHostMethod7 cb, uint64_t uniffi_handle, RustBuffer handle, uint64_t offset, uint32_t max_bytes, RustBuffer* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, handle, offset, max_bytes, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_HOST_METHOD8
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_HOST_METHOD8
typedef void (*UniffiCallbackInterfaceBindingHostMethod8)(uint64_t uniffi_handle, RustBuffer handle, uint64_t offset, RustBuffer bytes, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceBindingHostMethod8(
				UniffiCallbackInterfaceBindingHostMethod8 cb, uint64_t uniffi_handle, RustBuffer handle, uint64_t offset, RustBuffer bytes, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, handle, offset, bytes, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_HOST_METHOD9
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_HOST_METHOD9
typedef void (*UniffiCallbackInterfaceBindingHostMethod9)(uint64_t uniffi_handle, RustBuffer handle, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceBindingHostMethod9(
				UniffiCallbackInterfaceBindingHostMethod9 cb, uint64_t uniffi_handle, RustBuffer handle, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, handle, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_HOST_METHOD10
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_HOST_METHOD10
typedef void (*UniffiCallbackInterfaceBindingHostMethod10)(uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceBindingHostMethod10(
				UniffiCallbackInterfaceBindingHostMethod10 cb, uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_HOST_METHOD11
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_BINDING_HOST_METHOD11
typedef void (*UniffiCallbackInterfaceBindingHostMethod11)(uint64_t uniffi_handle, RustBuffer snapshot, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceBindingHostMethod11(
				UniffiCallbackInterfaceBindingHostMethod11 cb, uint64_t uniffi_handle, RustBuffer snapshot, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, snapshot, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_BINDING_ANALYTICS_HOST
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_BINDING_ANALYTICS_HOST
typedef struct UniffiVTableCallbackInterfaceBindingAnalyticsHost {
    UniffiCallbackInterfaceFree uniffiFree;
    UniffiCallbackInterfaceClone uniffiClone;
    UniffiCallbackInterfaceBindingAnalyticsHostMethod0 capture;
    UniffiCallbackInterfaceBindingAnalyticsHostMethod1 identify;
    UniffiCallbackInterfaceBindingAnalyticsHostMethod2 groupIdentify;
    UniffiCallbackInterfaceBindingAnalyticsHostMethod3 adoptSpacePerson;
    UniffiCallbackInterfaceBindingAnalyticsHostMethod4 releaseSpacePerson;
    UniffiCallbackInterfaceBindingAnalyticsHostMethod5 currentSpacePersonId;
    UniffiCallbackInterfaceBindingAnalyticsHostMethod6 resetTelemetryIdentity;
} UniffiVTableCallbackInterfaceBindingAnalyticsHost;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_BINDING_HOST
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_BINDING_HOST
typedef struct UniffiVTableCallbackInterfaceBindingHost {
    UniffiCallbackInterfaceFree uniffiFree;
    UniffiCallbackInterfaceClone uniffiClone;
    UniffiCallbackInterfaceBindingHostMethod0 privateDataDirectory;
    UniffiCallbackInterfaceBindingHostMethod1 cacheDirectory;
    UniffiCallbackInterfaceBindingHostMethod2 temporaryDirectory;
    UniffiCallbackInterfaceBindingHostMethod3 secureStorageGet;
    UniffiCallbackInterfaceBindingHostMethod4 secureStorageSet;
    UniffiCallbackInterfaceBindingHostMethod5 secureStorageDelete;
    UniffiCallbackInterfaceBindingHostMethod6 fileMetadata;
    UniffiCallbackInterfaceBindingHostMethod7 fileReadChunk;
    UniffiCallbackInterfaceBindingHostMethod8 fileWriteChunk;
    UniffiCallbackInterfaceBindingHostMethod9 fileFinishWrite;
    UniffiCallbackInterfaceBindingHostMethod10 clipboardRead;
    UniffiCallbackInterfaceBindingHostMethod11 clipboardWrite;
} UniffiVTableCallbackInterfaceBindingHost;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_CLONE_BINDINGANALYTICSHOST
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_CLONE_BINDINGANALYTICSHOST
uint64_t uniffi_uc_engine_uniffi_fn_clone_bindinganalyticshost(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_FREE_BINDINGANALYTICSHOST
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_FREE_BINDINGANALYTICSHOST
void uniffi_uc_engine_uniffi_fn_free_bindinganalyticshost(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_INIT_CALLBACK_VTABLE_BINDINGANALYTICSHOST
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_INIT_CALLBACK_VTABLE_BINDINGANALYTICSHOST
void uniffi_uc_engine_uniffi_fn_init_callback_vtable_bindinganalyticshost(UniffiVTableCallbackInterfaceBindingAnalyticsHost* vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGANALYTICSHOST_CAPTURE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGANALYTICSHOST_CAPTURE
void uniffi_uc_engine_uniffi_fn_method_bindinganalyticshost_capture(uint64_t ptr, RustBuffer event, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGANALYTICSHOST_IDENTIFY
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGANALYTICSHOST_IDENTIFY
void uniffi_uc_engine_uniffi_fn_method_bindinganalyticshost_identify(uint64_t ptr, RustBuffer payload, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGANALYTICSHOST_GROUP_IDENTIFY
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGANALYTICSHOST_GROUP_IDENTIFY
void uniffi_uc_engine_uniffi_fn_method_bindinganalyticshost_group_identify(uint64_t ptr, RustBuffer payload, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGANALYTICSHOST_ADOPT_SPACE_PERSON
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGANALYTICSHOST_ADOPT_SPACE_PERSON
RustBuffer uniffi_uc_engine_uniffi_fn_method_bindinganalyticshost_adopt_space_person(uint64_t ptr, RustBuffer space_person_id, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGANALYTICSHOST_RELEASE_SPACE_PERSON
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGANALYTICSHOST_RELEASE_SPACE_PERSON
RustBuffer uniffi_uc_engine_uniffi_fn_method_bindinganalyticshost_release_space_person(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGANALYTICSHOST_CURRENT_SPACE_PERSON_ID
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGANALYTICSHOST_CURRENT_SPACE_PERSON_ID
RustBuffer uniffi_uc_engine_uniffi_fn_method_bindinganalyticshost_current_space_person_id(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGANALYTICSHOST_RESET_TELEMETRY_IDENTITY
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGANALYTICSHOST_RESET_TELEMETRY_IDENTITY
RustBuffer uniffi_uc_engine_uniffi_fn_method_bindinganalyticshost_reset_telemetry_identity(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_CLONE_BINDINGHOST
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_CLONE_BINDINGHOST
uint64_t uniffi_uc_engine_uniffi_fn_clone_bindinghost(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_FREE_BINDINGHOST
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_FREE_BINDINGHOST
void uniffi_uc_engine_uniffi_fn_free_bindinghost(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_INIT_CALLBACK_VTABLE_BINDINGHOST
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_INIT_CALLBACK_VTABLE_BINDINGHOST
void uniffi_uc_engine_uniffi_fn_init_callback_vtable_bindinghost(UniffiVTableCallbackInterfaceBindingHost* vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGHOST_PRIVATE_DATA_DIRECTORY
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGHOST_PRIVATE_DATA_DIRECTORY
RustBuffer uniffi_uc_engine_uniffi_fn_method_bindinghost_private_data_directory(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGHOST_CACHE_DIRECTORY
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGHOST_CACHE_DIRECTORY
RustBuffer uniffi_uc_engine_uniffi_fn_method_bindinghost_cache_directory(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGHOST_TEMPORARY_DIRECTORY
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGHOST_TEMPORARY_DIRECTORY
RustBuffer uniffi_uc_engine_uniffi_fn_method_bindinghost_temporary_directory(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGHOST_SECURE_STORAGE_GET
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGHOST_SECURE_STORAGE_GET
RustBuffer uniffi_uc_engine_uniffi_fn_method_bindinghost_secure_storage_get(uint64_t ptr, RustBuffer key, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGHOST_SECURE_STORAGE_SET
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGHOST_SECURE_STORAGE_SET
void uniffi_uc_engine_uniffi_fn_method_bindinghost_secure_storage_set(uint64_t ptr, RustBuffer key, RustBuffer value, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGHOST_SECURE_STORAGE_DELETE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGHOST_SECURE_STORAGE_DELETE
void uniffi_uc_engine_uniffi_fn_method_bindinghost_secure_storage_delete(uint64_t ptr, RustBuffer key, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGHOST_FILE_METADATA
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGHOST_FILE_METADATA
RustBuffer uniffi_uc_engine_uniffi_fn_method_bindinghost_file_metadata(uint64_t ptr, RustBuffer handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGHOST_FILE_READ_CHUNK
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGHOST_FILE_READ_CHUNK
RustBuffer uniffi_uc_engine_uniffi_fn_method_bindinghost_file_read_chunk(uint64_t ptr, RustBuffer handle, uint64_t offset, uint32_t max_bytes, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGHOST_FILE_WRITE_CHUNK
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGHOST_FILE_WRITE_CHUNK
void uniffi_uc_engine_uniffi_fn_method_bindinghost_file_write_chunk(uint64_t ptr, RustBuffer handle, uint64_t offset, RustBuffer bytes, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGHOST_FILE_FINISH_WRITE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGHOST_FILE_FINISH_WRITE
void uniffi_uc_engine_uniffi_fn_method_bindinghost_file_finish_write(uint64_t ptr, RustBuffer handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGHOST_CLIPBOARD_READ
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGHOST_CLIPBOARD_READ
RustBuffer uniffi_uc_engine_uniffi_fn_method_bindinghost_clipboard_read(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGHOST_CLIPBOARD_WRITE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_BINDINGHOST_CLIPBOARD_WRITE
void uniffi_uc_engine_uniffi_fn_method_bindinghost_clipboard_write(uint64_t ptr, RustBuffer snapshot, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_CLONE_MOBILEENGINE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_CLONE_MOBILEENGINE
uint64_t uniffi_uc_engine_uniffi_fn_clone_mobileengine(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_FREE_MOBILEENGINE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_FREE_MOBILEENGINE
void uniffi_uc_engine_uniffi_fn_free_mobileengine(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_CONSTRUCTOR_MOBILEENGINE_START
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_CONSTRUCTOR_MOBILEENGINE_START
uint64_t uniffi_uc_engine_uniffi_fn_constructor_mobileengine_start(RustBuffer config, uint64_t host, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_CONSTRUCTOR_MOBILEENGINE_START_WITH_ANALYTICS
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_CONSTRUCTOR_MOBILEENGINE_START_WITH_ANALYTICS
uint64_t uniffi_uc_engine_uniffi_fn_constructor_mobileengine_start_with_analytics(RustBuffer config, uint64_t host, uint64_t analytics, RustBuffer context, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_CONSTRUCTOR_MOBILEENGINE_START_WITH_ANALYTICS_AND_LIFECYCLE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_CONSTRUCTOR_MOBILEENGINE_START_WITH_ANALYTICS_AND_LIFECYCLE
uint64_t uniffi_uc_engine_uniffi_fn_constructor_mobileengine_start_with_analytics_and_lifecycle(RustBuffer config, uint64_t host, uint64_t analytics, RustBuffer context, uint64_t lifecycle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_CONSTRUCTOR_MOBILEENGINE_START_WITH_LIFECYCLE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_CONSTRUCTOR_MOBILEENGINE_START_WITH_LIFECYCLE
uint64_t uniffi_uc_engine_uniffi_fn_constructor_mobileengine_start_with_lifecycle(RustBuffer config, uint64_t host, uint64_t lifecycle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_ADD_CUSTOM_RELAY
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_ADD_CUSTOM_RELAY
RustBuffer uniffi_uc_engine_uniffi_fn_method_mobileengine_add_custom_relay(uint64_t ptr, RustBuffer url, RustBuffer access_token, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_CANCEL_JOIN_SPACE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_CANCEL_JOIN_SPACE
RustBuffer uniffi_uc_engine_uniffi_fn_method_mobileengine_cancel_join_space(uint64_t ptr, RustBuffer join_id, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_CAPTURE_CURRENT_CLIPBOARD
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_CAPTURE_CURRENT_CLIPBOARD
RustBuffer uniffi_uc_engine_uniffi_fn_method_mobileengine_capture_current_clipboard(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_CHANGE_ENCRYPTION_PASSPHRASE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_CHANGE_ENCRYPTION_PASSPHRASE
void uniffi_uc_engine_uniffi_fn_method_mobileengine_change_encryption_passphrase(uint64_t ptr, RustBuffer passphrase, RustBuffer passphrase_confirmation, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_CHOOSE_DEVICE_GROUP
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_CHOOSE_DEVICE_GROUP
RustBuffer uniffi_uc_engine_uniffi_fn_method_mobileengine_choose_device_group(uint64_t ptr, RustBuffer issue_id, RustBuffer choice_id, uint64_t expected_revision, int8_t confirm_local_removal, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_CREATE_SPACE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_CREATE_SPACE
RustBuffer uniffi_uc_engine_uniffi_fn_method_mobileengine_create_space(uint64_t ptr, RustBuffer device_name, RustBuffer passphrase, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_DELETE_CUSTOM_RELAY
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_DELETE_CUSTOM_RELAY
RustBuffer uniffi_uc_engine_uniffi_fn_method_mobileengine_delete_custom_relay(uint64_t ptr, RustBuffer url, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_EDIT_CUSTOM_RELAY
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_EDIT_CUSTOM_RELAY
RustBuffer uniffi_uc_engine_uniffi_fn_method_mobileengine_edit_custom_relay(uint64_t ptr, RustBuffer previous_url, RustBuffer url, RustBuffer access_token, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_EXPORT_ENTRY
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_EXPORT_ENTRY
void uniffi_uc_engine_uniffi_fn_method_mobileengine_export_entry(uint64_t ptr, RustBuffer entry_id, RustBuffer destination_handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_ISSUE_INVITATION
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_ISSUE_INVITATION
RustBuffer uniffi_uc_engine_uniffi_fn_method_mobileengine_issue_invitation(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_JOIN_SPACE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_JOIN_SPACE
RustBuffer uniffi_uc_engine_uniffi_fn_method_mobileengine_join_space(uint64_t ptr, RustBuffer invitation_code, RustBuffer device_name, RustBuffer passphrase, int8_t preserve_unreadable_history, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_LEAVE_SPACE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_LEAVE_SPACE
void uniffi_uc_engine_uniffi_fn_method_mobileengine_leave_space(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_LIFECYCLE_STATE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_LIFECYCLE_STATE
RustBuffer uniffi_uc_engine_uniffi_fn_method_mobileengine_lifecycle_state(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_LIST_DEVICES
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_LIST_DEVICES
RustBuffer uniffi_uc_engine_uniffi_fn_method_mobileengine_list_devices(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_NEXT_EVENT
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_NEXT_EVENT
RustBuffer uniffi_uc_engine_uniffi_fn_method_mobileengine_next_event(uint64_t ptr, uint64_t timeout_ms, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_NOTIFY_CONNECTIVITY_OPPORTUNITY
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_NOTIFY_CONNECTIVITY_OPPORTUNITY
void uniffi_uc_engine_uniffi_fn_method_mobileengine_notify_connectivity_opportunity(uint64_t ptr, RustBuffer reason, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_OBSERVE_CLIPBOARD_CHANGE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_OBSERVE_CLIPBOARD_CHANGE
RustBuffer uniffi_uc_engine_uniffi_fn_method_mobileengine_observe_clipboard_change(uint64_t ptr, int8_t dispatch, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_QUERY_ACTIVE_CLIPBOARD
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_QUERY_ACTIVE_CLIPBOARD
RustBuffer uniffi_uc_engine_uniffi_fn_method_mobileengine_query_active_clipboard(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_QUERY_CUSTOM_RELAYS
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_QUERY_CUSTOM_RELAYS
RustBuffer uniffi_uc_engine_uniffi_fn_method_mobileengine_query_custom_relays(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_QUERY_DEVICE_GROUP_CHOICES
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_QUERY_DEVICE_GROUP_CHOICES
RustBuffer uniffi_uc_engine_uniffi_fn_method_mobileengine_query_device_group_choices(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_QUERY_LOCAL_DEVICE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_QUERY_LOCAL_DEVICE
RustBuffer uniffi_uc_engine_uniffi_fn_method_mobileengine_query_local_device(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_QUERY_NETWORK_RECOVERY_STATUS
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_QUERY_NETWORK_RECOVERY_STATUS
RustBuffer uniffi_uc_engine_uniffi_fn_method_mobileengine_query_network_recovery_status(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_QUERY_RELAY_OVERVIEW
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_QUERY_RELAY_OVERVIEW
RustBuffer uniffi_uc_engine_uniffi_fn_method_mobileengine_query_relay_overview(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_QUERY_SPACE_STATE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_QUERY_SPACE_STATE
RustBuffer uniffi_uc_engine_uniffi_fn_method_mobileengine_query_space_state(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_RECOVER_NETWORK
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_RECOVER_NETWORK
void uniffi_uc_engine_uniffi_fn_method_mobileengine_recover_network(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_RECOVER_SESSION
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_RECOVER_SESSION
RustBuffer uniffi_uc_engine_uniffi_fn_method_mobileengine_recover_session(uint64_t ptr, int8_t allow_secure_storage_unlock, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_REFRESH_PEER_CONNECTIONS
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_REFRESH_PEER_CONNECTIONS
RustBuffer uniffi_uc_engine_uniffi_fn_method_mobileengine_refresh_peer_connections(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_REMOVE_MEMBER
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_REMOVE_MEMBER
RustBuffer uniffi_uc_engine_uniffi_fn_method_mobileengine_remove_member(uint64_t ptr, RustBuffer device_id, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_RESEND_ENTRY
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_RESEND_ENTRY
RustBuffer uniffi_uc_engine_uniffi_fn_method_mobileengine_resend_entry(uint64_t ptr, RustBuffer entry_id, RustBuffer target_devices, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_RESTORE_CLIPBOARD
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_RESTORE_CLIPBOARD
RustBuffer uniffi_uc_engine_uniffi_fn_method_mobileengine_restore_clipboard(uint64_t ptr, RustBuffer entry_id, RustBuffer mode, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_RESUME
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_RESUME
void uniffi_uc_engine_uniffi_fn_method_mobileengine_resume(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_SAVE_CUSTOM_RELAY
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_SAVE_CUSTOM_RELAY
RustBuffer uniffi_uc_engine_uniffi_fn_method_mobileengine_save_custom_relay(uint64_t ptr, RustBuffer url, RustBuffer access_token, RustBuffer previous_url, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_SEND_FILES
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_SEND_FILES
RustBuffer uniffi_uc_engine_uniffi_fn_method_mobileengine_send_files(uint64_t ptr, RustBuffer file_handles, RustBuffer target_devices, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_SEND_IMAGE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_SEND_IMAGE
RustBuffer uniffi_uc_engine_uniffi_fn_method_mobileengine_send_image(uint64_t ptr, RustBuffer bytes, RustBuffer mime_type, RustBuffer target_devices, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_SEND_TEXT
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_SEND_TEXT
RustBuffer uniffi_uc_engine_uniffi_fn_method_mobileengine_send_text(uint64_t ptr, RustBuffer text, RustBuffer target_devices, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_SHUTDOWN
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_SHUTDOWN
void uniffi_uc_engine_uniffi_fn_method_mobileengine_shutdown(uint64_t ptr, uint64_t deadline_ms, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_SUSPEND
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_SUSPEND
void uniffi_uc_engine_uniffi_fn_method_mobileengine_suspend(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_SUSPEND_WITH_DEADLINE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILEENGINE_SUSPEND_WITH_DEADLINE
void uniffi_uc_engine_uniffi_fn_method_mobileengine_suspend_with_deadline(uint64_t ptr, uint64_t deadline_ms, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_CLONE_MOBILESTARTUPLIFECYCLE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_CLONE_MOBILESTARTUPLIFECYCLE
uint64_t uniffi_uc_engine_uniffi_fn_clone_mobilestartuplifecycle(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_FREE_MOBILESTARTUPLIFECYCLE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_FREE_MOBILESTARTUPLIFECYCLE
void uniffi_uc_engine_uniffi_fn_free_mobilestartuplifecycle(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_CONSTRUCTOR_MOBILESTARTUPLIFECYCLE_NEW
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_CONSTRUCTOR_MOBILESTARTUPLIFECYCLE_NEW
uint64_t uniffi_uc_engine_uniffi_fn_constructor_mobilestartuplifecycle_new(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILESTARTUPLIFECYCLE_RESUME
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILESTARTUPLIFECYCLE_RESUME
void uniffi_uc_engine_uniffi_fn_method_mobilestartuplifecycle_resume(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILESTARTUPLIFECYCLE_SUSPEND
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILESTARTUPLIFECYCLE_SUSPEND
void uniffi_uc_engine_uniffi_fn_method_mobilestartuplifecycle_suspend(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILESTARTUPLIFECYCLE_SUSPEND_WITH_DEADLINE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_METHOD_MOBILESTARTUPLIFECYCLE_SUSPEND_WITH_DEADLINE
void uniffi_uc_engine_uniffi_fn_method_mobilestartuplifecycle_suspend_with_deadline(uint64_t ptr, uint64_t deadline_ms, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_FUNC_CORE_VERSION
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_FUNC_CORE_VERSION
RustBuffer uniffi_uc_engine_uniffi_fn_func_core_version(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_FUNC_FLUSH_PROCESS_OBSERVABILITY
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_FUNC_FLUSH_PROCESS_OBSERVABILITY
RustBuffer uniffi_uc_engine_uniffi_fn_func_flush_process_observability(uint64_t deadline_ms, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_FUNC_INSTALL_PROCESS_OBSERVABILITY
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_FUNC_INSTALL_PROCESS_OBSERVABILITY
RustBuffer uniffi_uc_engine_uniffi_fn_func_install_process_observability(RustBuffer config, uint64_t host, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_FUNC_QUERY_PROCESS_OBSERVABILITY_HEALTH
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_FUNC_QUERY_PROCESS_OBSERVABILITY_HEALTH
RustBuffer uniffi_uc_engine_uniffi_fn_func_query_process_observability_health(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_FUNC_SHUTDOWN_PROCESS_OBSERVABILITY
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_FUNC_SHUTDOWN_PROCESS_OBSERVABILITY
RustBuffer uniffi_uc_engine_uniffi_fn_func_shutdown_process_observability(uint64_t deadline_ms, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_FUNC_PREPARE_LOCAL_DIAGNOSTIC_EXPORT
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_FUNC_PREPARE_LOCAL_DIAGNOSTIC_EXPORT
RustBuffer uniffi_uc_engine_uniffi_fn_func_prepare_local_diagnostic_export(uint64_t deadline_ms, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_FUNC_QUERY_LOCAL_DIAGNOSTIC_STATUS
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_FUNC_QUERY_LOCAL_DIAGNOSTIC_STATUS
RustBuffer uniffi_uc_engine_uniffi_fn_func_query_local_diagnostic_status(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_FUNC_RECORD_HOST_DIAGNOSTIC
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_FUNC_RECORD_HOST_DIAGNOSTIC
RustBuffer uniffi_uc_engine_uniffi_fn_func_record_host_diagnostic(RustBuffer source, RustBuffer event, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_FUNC_REGISTER_HOST_DIAGNOSTIC_SOURCE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_FUNC_REGISTER_HOST_DIAGNOSTIC_SOURCE
void uniffi_uc_engine_uniffi_fn_func_register_host_diagnostic_source(RustBuffer source, RustBuffer capability, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_FUNC_START_LOCAL_DIAGNOSTIC_CAPTURE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_FUNC_START_LOCAL_DIAGNOSTIC_CAPTURE
RustBuffer uniffi_uc_engine_uniffi_fn_func_start_local_diagnostic_capture(uint64_t duration_ms, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_FUNC_STOP_LOCAL_DIAGNOSTIC_CAPTURE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_FN_FUNC_STOP_LOCAL_DIAGNOSTIC_CAPTURE
RustBuffer uniffi_uc_engine_uniffi_fn_func_stop_local_diagnostic_capture(RustBuffer capture_id, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUSTBUFFER_ALLOC
RustBuffer ffi_uc_engine_uniffi_rustbuffer_alloc(uint64_t size, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_uc_engine_uniffi_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUSTBUFFER_FREE
void ffi_uc_engine_uniffi_rustbuffer_free(RustBuffer buf, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUSTBUFFER_RESERVE
RustBuffer ffi_uc_engine_uniffi_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_POLL_U8
void ffi_uc_engine_uniffi_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_CANCEL_U8
void ffi_uc_engine_uniffi_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_FREE_U8
void ffi_uc_engine_uniffi_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_uc_engine_uniffi_rust_future_complete_u8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_POLL_I8
void ffi_uc_engine_uniffi_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_CANCEL_I8
void ffi_uc_engine_uniffi_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_FREE_I8
void ffi_uc_engine_uniffi_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_COMPLETE_I8
int8_t ffi_uc_engine_uniffi_rust_future_complete_i8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_POLL_U16
void ffi_uc_engine_uniffi_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_CANCEL_U16
void ffi_uc_engine_uniffi_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_FREE_U16
void ffi_uc_engine_uniffi_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_uc_engine_uniffi_rust_future_complete_u16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_POLL_I16
void ffi_uc_engine_uniffi_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_CANCEL_I16
void ffi_uc_engine_uniffi_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_FREE_I16
void ffi_uc_engine_uniffi_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_COMPLETE_I16
int16_t ffi_uc_engine_uniffi_rust_future_complete_i16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_POLL_U32
void ffi_uc_engine_uniffi_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_CANCEL_U32
void ffi_uc_engine_uniffi_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_FREE_U32
void ffi_uc_engine_uniffi_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_uc_engine_uniffi_rust_future_complete_u32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_POLL_I32
void ffi_uc_engine_uniffi_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_CANCEL_I32
void ffi_uc_engine_uniffi_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_FREE_I32
void ffi_uc_engine_uniffi_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_COMPLETE_I32
int32_t ffi_uc_engine_uniffi_rust_future_complete_i32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_POLL_U64
void ffi_uc_engine_uniffi_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_CANCEL_U64
void ffi_uc_engine_uniffi_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_FREE_U64
void ffi_uc_engine_uniffi_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_uc_engine_uniffi_rust_future_complete_u64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_POLL_I64
void ffi_uc_engine_uniffi_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_CANCEL_I64
void ffi_uc_engine_uniffi_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_FREE_I64
void ffi_uc_engine_uniffi_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_COMPLETE_I64
int64_t ffi_uc_engine_uniffi_rust_future_complete_i64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_POLL_F32
void ffi_uc_engine_uniffi_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_CANCEL_F32
void ffi_uc_engine_uniffi_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_FREE_F32
void ffi_uc_engine_uniffi_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_COMPLETE_F32
float ffi_uc_engine_uniffi_rust_future_complete_f32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_POLL_F64
void ffi_uc_engine_uniffi_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_CANCEL_F64
void ffi_uc_engine_uniffi_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_FREE_F64
void ffi_uc_engine_uniffi_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_COMPLETE_F64
double ffi_uc_engine_uniffi_rust_future_complete_f64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_uc_engine_uniffi_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_uc_engine_uniffi_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_uc_engine_uniffi_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_uc_engine_uniffi_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_POLL_VOID
void ffi_uc_engine_uniffi_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_CANCEL_VOID
void ffi_uc_engine_uniffi_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_FREE_VOID
void ffi_uc_engine_uniffi_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_RUST_FUTURE_COMPLETE_VOID
void ffi_uc_engine_uniffi_rust_future_complete_void(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_FUNC_CORE_VERSION
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_FUNC_CORE_VERSION
uint16_t uniffi_uc_engine_uniffi_checksum_func_core_version(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_FUNC_FLUSH_PROCESS_OBSERVABILITY
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_FUNC_FLUSH_PROCESS_OBSERVABILITY
uint16_t uniffi_uc_engine_uniffi_checksum_func_flush_process_observability(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_FUNC_INSTALL_PROCESS_OBSERVABILITY
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_FUNC_INSTALL_PROCESS_OBSERVABILITY
uint16_t uniffi_uc_engine_uniffi_checksum_func_install_process_observability(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_FUNC_QUERY_PROCESS_OBSERVABILITY_HEALTH
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_FUNC_QUERY_PROCESS_OBSERVABILITY_HEALTH
uint16_t uniffi_uc_engine_uniffi_checksum_func_query_process_observability_health(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_FUNC_SHUTDOWN_PROCESS_OBSERVABILITY
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_FUNC_SHUTDOWN_PROCESS_OBSERVABILITY
uint16_t uniffi_uc_engine_uniffi_checksum_func_shutdown_process_observability(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_FUNC_PREPARE_LOCAL_DIAGNOSTIC_EXPORT
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_FUNC_PREPARE_LOCAL_DIAGNOSTIC_EXPORT
uint16_t uniffi_uc_engine_uniffi_checksum_func_prepare_local_diagnostic_export(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_FUNC_QUERY_LOCAL_DIAGNOSTIC_STATUS
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_FUNC_QUERY_LOCAL_DIAGNOSTIC_STATUS
uint16_t uniffi_uc_engine_uniffi_checksum_func_query_local_diagnostic_status(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_FUNC_RECORD_HOST_DIAGNOSTIC
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_FUNC_RECORD_HOST_DIAGNOSTIC
uint16_t uniffi_uc_engine_uniffi_checksum_func_record_host_diagnostic(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_FUNC_REGISTER_HOST_DIAGNOSTIC_SOURCE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_FUNC_REGISTER_HOST_DIAGNOSTIC_SOURCE
uint16_t uniffi_uc_engine_uniffi_checksum_func_register_host_diagnostic_source(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_FUNC_START_LOCAL_DIAGNOSTIC_CAPTURE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_FUNC_START_LOCAL_DIAGNOSTIC_CAPTURE
uint16_t uniffi_uc_engine_uniffi_checksum_func_start_local_diagnostic_capture(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_FUNC_STOP_LOCAL_DIAGNOSTIC_CAPTURE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_FUNC_STOP_LOCAL_DIAGNOSTIC_CAPTURE
uint16_t uniffi_uc_engine_uniffi_checksum_func_stop_local_diagnostic_capture(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGANALYTICSHOST_CAPTURE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGANALYTICSHOST_CAPTURE
uint16_t uniffi_uc_engine_uniffi_checksum_method_bindinganalyticshost_capture(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGANALYTICSHOST_IDENTIFY
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGANALYTICSHOST_IDENTIFY
uint16_t uniffi_uc_engine_uniffi_checksum_method_bindinganalyticshost_identify(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGANALYTICSHOST_GROUP_IDENTIFY
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGANALYTICSHOST_GROUP_IDENTIFY
uint16_t uniffi_uc_engine_uniffi_checksum_method_bindinganalyticshost_group_identify(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGANALYTICSHOST_ADOPT_SPACE_PERSON
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGANALYTICSHOST_ADOPT_SPACE_PERSON
uint16_t uniffi_uc_engine_uniffi_checksum_method_bindinganalyticshost_adopt_space_person(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGANALYTICSHOST_RELEASE_SPACE_PERSON
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGANALYTICSHOST_RELEASE_SPACE_PERSON
uint16_t uniffi_uc_engine_uniffi_checksum_method_bindinganalyticshost_release_space_person(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGANALYTICSHOST_CURRENT_SPACE_PERSON_ID
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGANALYTICSHOST_CURRENT_SPACE_PERSON_ID
uint16_t uniffi_uc_engine_uniffi_checksum_method_bindinganalyticshost_current_space_person_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGANALYTICSHOST_RESET_TELEMETRY_IDENTITY
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGANALYTICSHOST_RESET_TELEMETRY_IDENTITY
uint16_t uniffi_uc_engine_uniffi_checksum_method_bindinganalyticshost_reset_telemetry_identity(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGHOST_PRIVATE_DATA_DIRECTORY
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGHOST_PRIVATE_DATA_DIRECTORY
uint16_t uniffi_uc_engine_uniffi_checksum_method_bindinghost_private_data_directory(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGHOST_CACHE_DIRECTORY
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGHOST_CACHE_DIRECTORY
uint16_t uniffi_uc_engine_uniffi_checksum_method_bindinghost_cache_directory(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGHOST_TEMPORARY_DIRECTORY
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGHOST_TEMPORARY_DIRECTORY
uint16_t uniffi_uc_engine_uniffi_checksum_method_bindinghost_temporary_directory(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGHOST_SECURE_STORAGE_GET
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGHOST_SECURE_STORAGE_GET
uint16_t uniffi_uc_engine_uniffi_checksum_method_bindinghost_secure_storage_get(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGHOST_SECURE_STORAGE_SET
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGHOST_SECURE_STORAGE_SET
uint16_t uniffi_uc_engine_uniffi_checksum_method_bindinghost_secure_storage_set(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGHOST_SECURE_STORAGE_DELETE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGHOST_SECURE_STORAGE_DELETE
uint16_t uniffi_uc_engine_uniffi_checksum_method_bindinghost_secure_storage_delete(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGHOST_FILE_METADATA
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGHOST_FILE_METADATA
uint16_t uniffi_uc_engine_uniffi_checksum_method_bindinghost_file_metadata(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGHOST_FILE_READ_CHUNK
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGHOST_FILE_READ_CHUNK
uint16_t uniffi_uc_engine_uniffi_checksum_method_bindinghost_file_read_chunk(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGHOST_FILE_WRITE_CHUNK
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGHOST_FILE_WRITE_CHUNK
uint16_t uniffi_uc_engine_uniffi_checksum_method_bindinghost_file_write_chunk(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGHOST_FILE_FINISH_WRITE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGHOST_FILE_FINISH_WRITE
uint16_t uniffi_uc_engine_uniffi_checksum_method_bindinghost_file_finish_write(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGHOST_CLIPBOARD_READ
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGHOST_CLIPBOARD_READ
uint16_t uniffi_uc_engine_uniffi_checksum_method_bindinghost_clipboard_read(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGHOST_CLIPBOARD_WRITE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_BINDINGHOST_CLIPBOARD_WRITE
uint16_t uniffi_uc_engine_uniffi_checksum_method_bindinghost_clipboard_write(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_ADD_CUSTOM_RELAY
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_ADD_CUSTOM_RELAY
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_add_custom_relay(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_CANCEL_JOIN_SPACE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_CANCEL_JOIN_SPACE
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_cancel_join_space(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_CAPTURE_CURRENT_CLIPBOARD
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_CAPTURE_CURRENT_CLIPBOARD
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_capture_current_clipboard(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_CHANGE_ENCRYPTION_PASSPHRASE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_CHANGE_ENCRYPTION_PASSPHRASE
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_change_encryption_passphrase(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_CHOOSE_DEVICE_GROUP
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_CHOOSE_DEVICE_GROUP
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_choose_device_group(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_CREATE_SPACE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_CREATE_SPACE
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_create_space(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_DELETE_CUSTOM_RELAY
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_DELETE_CUSTOM_RELAY
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_delete_custom_relay(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_EDIT_CUSTOM_RELAY
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_EDIT_CUSTOM_RELAY
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_edit_custom_relay(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_EXPORT_ENTRY
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_EXPORT_ENTRY
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_export_entry(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_ISSUE_INVITATION
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_ISSUE_INVITATION
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_issue_invitation(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_JOIN_SPACE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_JOIN_SPACE
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_join_space(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_LEAVE_SPACE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_LEAVE_SPACE
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_leave_space(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_LIFECYCLE_STATE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_LIFECYCLE_STATE
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_lifecycle_state(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_LIST_DEVICES
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_LIST_DEVICES
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_list_devices(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_NEXT_EVENT
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_NEXT_EVENT
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_next_event(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_NOTIFY_CONNECTIVITY_OPPORTUNITY
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_NOTIFY_CONNECTIVITY_OPPORTUNITY
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_notify_connectivity_opportunity(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_OBSERVE_CLIPBOARD_CHANGE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_OBSERVE_CLIPBOARD_CHANGE
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_observe_clipboard_change(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_QUERY_ACTIVE_CLIPBOARD
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_QUERY_ACTIVE_CLIPBOARD
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_query_active_clipboard(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_QUERY_CUSTOM_RELAYS
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_QUERY_CUSTOM_RELAYS
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_query_custom_relays(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_QUERY_DEVICE_GROUP_CHOICES
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_QUERY_DEVICE_GROUP_CHOICES
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_query_device_group_choices(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_QUERY_LOCAL_DEVICE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_QUERY_LOCAL_DEVICE
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_query_local_device(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_QUERY_NETWORK_RECOVERY_STATUS
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_QUERY_NETWORK_RECOVERY_STATUS
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_query_network_recovery_status(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_QUERY_RELAY_OVERVIEW
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_QUERY_RELAY_OVERVIEW
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_query_relay_overview(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_QUERY_SPACE_STATE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_QUERY_SPACE_STATE
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_query_space_state(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_RECOVER_NETWORK
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_RECOVER_NETWORK
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_recover_network(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_RECOVER_SESSION
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_RECOVER_SESSION
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_recover_session(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_REFRESH_PEER_CONNECTIONS
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_REFRESH_PEER_CONNECTIONS
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_refresh_peer_connections(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_REMOVE_MEMBER
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_REMOVE_MEMBER
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_remove_member(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_RESEND_ENTRY
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_RESEND_ENTRY
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_resend_entry(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_RESTORE_CLIPBOARD
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_RESTORE_CLIPBOARD
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_restore_clipboard(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_RESUME
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_RESUME
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_resume(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_SAVE_CUSTOM_RELAY
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_SAVE_CUSTOM_RELAY
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_save_custom_relay(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_SEND_FILES
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_SEND_FILES
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_send_files(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_SEND_IMAGE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_SEND_IMAGE
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_send_image(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_SEND_TEXT
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_SEND_TEXT
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_send_text(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_SHUTDOWN
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_SHUTDOWN
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_shutdown(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_SUSPEND
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_SUSPEND
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_suspend(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_SUSPEND_WITH_DEADLINE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILEENGINE_SUSPEND_WITH_DEADLINE
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobileengine_suspend_with_deadline(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILESTARTUPLIFECYCLE_RESUME
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILESTARTUPLIFECYCLE_RESUME
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobilestartuplifecycle_resume(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILESTARTUPLIFECYCLE_SUSPEND
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILESTARTUPLIFECYCLE_SUSPEND
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobilestartuplifecycle_suspend(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILESTARTUPLIFECYCLE_SUSPEND_WITH_DEADLINE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_METHOD_MOBILESTARTUPLIFECYCLE_SUSPEND_WITH_DEADLINE
uint16_t uniffi_uc_engine_uniffi_checksum_method_mobilestartuplifecycle_suspend_with_deadline(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_CONSTRUCTOR_MOBILEENGINE_START
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_CONSTRUCTOR_MOBILEENGINE_START
uint16_t uniffi_uc_engine_uniffi_checksum_constructor_mobileengine_start(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_CONSTRUCTOR_MOBILEENGINE_START_WITH_ANALYTICS
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_CONSTRUCTOR_MOBILEENGINE_START_WITH_ANALYTICS
uint16_t uniffi_uc_engine_uniffi_checksum_constructor_mobileengine_start_with_analytics(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_CONSTRUCTOR_MOBILEENGINE_START_WITH_ANALYTICS_AND_LIFECYCLE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_CONSTRUCTOR_MOBILEENGINE_START_WITH_ANALYTICS_AND_LIFECYCLE
uint16_t uniffi_uc_engine_uniffi_checksum_constructor_mobileengine_start_with_analytics_and_lifecycle(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_CONSTRUCTOR_MOBILEENGINE_START_WITH_LIFECYCLE
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_CONSTRUCTOR_MOBILEENGINE_START_WITH_LIFECYCLE
uint16_t uniffi_uc_engine_uniffi_checksum_constructor_mobileengine_start_with_lifecycle(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_CONSTRUCTOR_MOBILESTARTUPLIFECYCLE_NEW
#define UNIFFI_FFIDEF_UNIFFI_UC_ENGINE_UNIFFI_CHECKSUM_CONSTRUCTOR_MOBILESTARTUPLIFECYCLE_NEW
uint16_t uniffi_uc_engine_uniffi_checksum_constructor_mobilestartuplifecycle_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_UC_ENGINE_UNIFFI_UNIFFI_CONTRACT_VERSION
uint32_t ffi_uc_engine_uniffi_uniffi_contract_version(void
    
);
#endif

 void uc_engine_uniffi_cgo_dispatchCallbackInterfaceBindingAnalyticsHostMethod0(uint64_t uniffi_handle, RustBuffer event, void* uniffi_out_return, RustCallStatus* callStatus );
 void uc_engine_uniffi_cgo_dispatchCallbackInterfaceBindingAnalyticsHostMethod1(uint64_t uniffi_handle, RustBuffer payload, void* uniffi_out_return, RustCallStatus* callStatus );
 void uc_engine_uniffi_cgo_dispatchCallbackInterfaceBindingAnalyticsHostMethod2(uint64_t uniffi_handle, RustBuffer payload, void* uniffi_out_return, RustCallStatus* callStatus );
 void uc_engine_uniffi_cgo_dispatchCallbackInterfaceBindingAnalyticsHostMethod3(uint64_t uniffi_handle, RustBuffer space_person_id, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );
 void uc_engine_uniffi_cgo_dispatchCallbackInterfaceBindingAnalyticsHostMethod4(uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );
 void uc_engine_uniffi_cgo_dispatchCallbackInterfaceBindingAnalyticsHostMethod5(uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );
 void uc_engine_uniffi_cgo_dispatchCallbackInterfaceBindingAnalyticsHostMethod6(uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );
 void uc_engine_uniffi_cgo_dispatchCallbackInterfaceBindingAnalyticsHostFree(uint64_t handle);
uint64_t uc_engine_uniffi_cgo_dispatchCallbackInterfaceBindingAnalyticsHostClone(uint64_t handle);
 void uc_engine_uniffi_cgo_dispatchCallbackInterfaceBindingHostMethod0(uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );
 void uc_engine_uniffi_cgo_dispatchCallbackInterfaceBindingHostMethod1(uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );
 void uc_engine_uniffi_cgo_dispatchCallbackInterfaceBindingHostMethod2(uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );
 void uc_engine_uniffi_cgo_dispatchCallbackInterfaceBindingHostMethod3(uint64_t uniffi_handle, RustBuffer key, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );
 void uc_engine_uniffi_cgo_dispatchCallbackInterfaceBindingHostMethod4(uint64_t uniffi_handle, RustBuffer key, RustBuffer value, void* uniffi_out_return, RustCallStatus* callStatus );
 void uc_engine_uniffi_cgo_dispatchCallbackInterfaceBindingHostMethod5(uint64_t uniffi_handle, RustBuffer key, void* uniffi_out_return, RustCallStatus* callStatus );
 void uc_engine_uniffi_cgo_dispatchCallbackInterfaceBindingHostMethod6(uint64_t uniffi_handle, RustBuffer handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );
 void uc_engine_uniffi_cgo_dispatchCallbackInterfaceBindingHostMethod7(uint64_t uniffi_handle, RustBuffer handle, uint64_t offset, uint32_t max_bytes, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );
 void uc_engine_uniffi_cgo_dispatchCallbackInterfaceBindingHostMethod8(uint64_t uniffi_handle, RustBuffer handle, uint64_t offset, RustBuffer bytes, void* uniffi_out_return, RustCallStatus* callStatus );
 void uc_engine_uniffi_cgo_dispatchCallbackInterfaceBindingHostMethod9(uint64_t uniffi_handle, RustBuffer handle, void* uniffi_out_return, RustCallStatus* callStatus );
 void uc_engine_uniffi_cgo_dispatchCallbackInterfaceBindingHostMethod10(uint64_t uniffi_handle, RustBuffer* uniffi_out_return, RustCallStatus* callStatus );
 void uc_engine_uniffi_cgo_dispatchCallbackInterfaceBindingHostMethod11(uint64_t uniffi_handle, RustBuffer snapshot, void* uniffi_out_return, RustCallStatus* callStatus );
 void uc_engine_uniffi_cgo_dispatchCallbackInterfaceBindingHostFree(uint64_t handle);
uint64_t uc_engine_uniffi_cgo_dispatchCallbackInterfaceBindingHostClone(uint64_t handle);
